-- =============================================================
--  ドメイン駆動設計実践 Java編 — サンプルDB定義 (PostgreSQL)
--  データベース名: restapi_exercise
--  テーブル: product_category / product / product_stock
--  ※テキストのテーブル定義書・概念ドメインモデルに準拠
-- =============================================================


-- =============================================================
-- 1. テーブル定義
-- =============================================================

-- 再実行できるように、依存関係の逆順で削除
DROP TABLE IF EXISTS product_stock    CASCADE;
DROP TABLE IF EXISTS product          CASCADE;
DROP TABLE IF EXISTS product_category CASCADE;

-- -------------------------------------------------------------
-- 1-1. カテゴリ (product_category)
-- -------------------------------------------------------------
CREATE TABLE product_category (
    id            INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- カテゴリId（自動生成）
    category_uuid VARCHAR(36)  NOT NULL UNIQUE,                                -- 識別Id（ドメインの識別子）
    name          VARCHAR(20)  NOT NULL UNIQUE                                 -- カテゴリ名（空白不可・重複不可）
);

COMMENT ON TABLE  product_category               IS 'カテゴリ';
COMMENT ON COLUMN product_category.id            IS 'カテゴリId（主キー・自動生成）';
COMMENT ON COLUMN product_category.category_uuid IS '識別Id（コード上の識別に利用）';
COMMENT ON COLUMN product_category.name          IS 'カテゴリ名';

-- -------------------------------------------------------------
-- 1-2. 商品 (product)
--   カテゴリ 1 : 商品 多  （category_id が外部キー）
-- -------------------------------------------------------------
CREATE TABLE product (
    id           INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,   -- 商品Id（自動生成）
    product_uuid VARCHAR(36)  NOT NULL UNIQUE,                                -- 識別Id
    name         VARCHAR(30)  NOT NULL UNIQUE,                                -- 商品名（空白不可・重複不可）
    price        INTEGER      NOT NULL CHECK (price BETWEEN 50 AND 10000),    -- 単価（50〜10000）
    category_id  INTEGER      NOT NULL
        REFERENCES product_category (id) ON DELETE RESTRICT                    -- 商品カテゴリId（外部キー）
);

COMMENT ON TABLE  product              IS '商品';
COMMENT ON COLUMN product.id           IS '商品Id（主キー・自動生成）';
COMMENT ON COLUMN product.product_uuid IS '識別Id（コード上の識別に利用）';
COMMENT ON COLUMN product.name         IS '商品名';
COMMENT ON COLUMN product.price        IS '単価（50〜10000円）';
COMMENT ON COLUMN product.category_id  IS '商品カテゴリId（product_category.id への外部キー）';

CREATE INDEX idx_product_category_id ON product (category_id);

-- -------------------------------------------------------------
-- 1-3. 商品在庫 (product_stock)
--   商品 1 : 在庫 1  （product_id を UNIQUE にして 1:1 を担保）
-- -------------------------------------------------------------
CREATE TABLE product_stock (
    id         INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,     -- 在庫Id（自動生成）
    stock_uuid VARCHAR(36)  NOT NULL UNIQUE,                                  -- 識別Id
    stock      INTEGER      NOT NULL CHECK (stock >= 0),                      -- 在庫数（0以上）
    product_id INTEGER      NOT NULL UNIQUE
        REFERENCES product (id) ON DELETE CASCADE                             -- 商品Id（外部キー・1:1）
);
-- ※ユビキタス言語では「100超不可」の記述もあります。上限も課すなら
--   CHECK (stock >= 0)  →  CHECK (stock BETWEEN 0 AND 100)  に変更してください。

COMMENT ON TABLE  product_stock            IS '商品在庫';
COMMENT ON COLUMN product_stock.id         IS '在庫Id（主キー・自動生成）';
COMMENT ON COLUMN product_stock.stock_uuid IS '識別Id（コード上の識別に利用）';
COMMENT ON COLUMN product_stock.stock      IS '在庫数';
COMMENT ON COLUMN product_stock.product_id IS '商品Id（product.id への外部キー・1商品1在庫）';
